### ISSUE TITLE
Error don't work on django 1.6 mezzanine 3.1.10

### ISSUE THREAD

**Issue by tabatabaei** [catalpainternational/mezzanine_modeltranslation#1]
$python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    from django.core.management import execute_manager
ImportError: cannot import name execute_manager
